### PR TITLE
LemnaTec: Added Several Vegetation Indices

### PR DESCRIPTION
**Pull request by ac-gl-chris**
I added several vegetation indices to the script.
Some require wavelengths which may not be available. I was not able to test the code so please have a look.

Christopher Schardt (LemnaTec)

### CODE REVIEW

**Comment by dlebauer** [comment]
Chris - 

Thank you for your contributions but this code is deprecated and had been replaced by the extractors-hyperspectral repository

Could you please submit your pull request there? It will likely two some updates.

Might be a good idea for you to coordinate directly with Henry @hmb1 

@hmb1 could you please remove all deprecated scripts from those repo? Can you give Chris access to the VM you are using so that he can test  (and write tests for) his code?

**Comment by solmazhajmohammadi** [comment]
@hmb1 how we can iterate through sets of indices in NCO?
tnx

**Comment by hmb1** [comment]
HI Chris,
 I will manually merge your changes as I have an updated version I am working on a later version that has not been formally pushed.. I will put the latest version on the VM machine ( the machine is 141.142.170.146 )  
Ask @craig-willis for  alogin to the machine 

...Henry

**Comment by hmb1** [comment]
Solmaz,
 can you post the algorithms /  formulas you want implemented please
 And I'll see what I can do 
...Henry

**Comment by solmazhajmohammadi** [comment]
for example: The SG is the mean of reflectance across the 500 nm to 600 nm

**Comment by hmb1** [comment]
HI Somaz,
 below is a code snippet that calculates the pixel mean across R500-R600
 It is on ROGER at location     **/home/butowskh/rgr/SG.nco**  along with an example run SG.nc
please let me know if this is what you want.

`   // example of iterating over wavelengths

srt=min_coords(wavelength,5.0e-7);
end=min_coords(wavelength,6.0e-7);

// double check ranges

print(wavelength(srt));
print(wavelength(end));

if( fabs(wavelength(srt)-5.0e-7) > 0.01e-7d )
{
  print("wavelength R500 not in wavelength coord\n");
  exit(1);
}

if( fabs(wavelength(end)-6.0e-7) > 0.01e-7d )
{
  print("wavelength R600 not in wavelength coord\n");
  exit(1);
}

idx=0;

SG=rfl_img(srt,:,:);

for(idx=srt+1;idx<=end;idx++)
  SG+= rfl_img(idx,:,:);

// calculate mean
SG=SG / (end-srt+1);
 `

**Comment by hmb1** [comment]
@ac-gl-chris 
"DWSI-1","DWSI-2","DWSI-3","DWSI-4","DWSI-5"

The above vars will have be renamed as '-' means subtract 

@hmb1

**Comment by ac-gl-chris** [comment]
Hi, sorry I was off work.
@hmb1, so from what I understood, Henry you took the code from the pull request and done some changes on a local repo? Do you need any contribution from me? 
However, I don't know how to run the nco script at all. So without someone showing me accessing the VM would make no sense I guess :)

Chris

**Comment by craig-willis** [comment]
Chris -- please email me at willis8@illinois.edu for access.

**Comment by hmb1** [comment]
HI  Christoper,
 I added your indices (phew) to the main ncap2 script please review it on the pull request
[](url)https://github.com/terraref/extractors-hyperspectral/pull/20

...Henry

**Comment by hmb1** [comment]
Hi @ac-gl-chris ,
 the ncap2 script is now in good shape. Please pull master branch from []https://github.com/terraref/extractors-hyperspectral/(url)
When you have a moment  Ill gibe you a quick tutorial on how to run ncap2 script and the most essential commands in NCO 
...Henry

**Comment by hmb1** [comment]
@ac-gl-chris 
please add the meta-data as you wish 
...Henry

**Comment by ac-gl-chris** [comment]
@hmb1 Craig sent me a short description on how to access the workbench and use the docker environment to call the hyperspectral_workflow.sh
Going to try it...
Chris

**Comment by hmb1** [comment]
HI @ac-gl-chris 
When you have a moment ill give you a quick intro to NCO and cnap2
...HEnry

**Comment by ac-gl-chris** [comment]
@hmb1 With the help of Craig I was able to run the hyperspectral_workflow. But I don't know how to interpret the output. What is the output?
I'm off work for weekend now, maybe you can give me a quick overview how the system is actually working, never heard of nco or ncap :)

Chris

**Comment by hmb1** [comment]
HI Chris
  let me know when your free next week.
  If can read up a little on netCDF files that would help
  ...Henry

**Comment by dlebauer** [comment]
@ac-gl-chris you can also 
1. open the file in something like Panoply
2. take a look at (and extend) the tutorials https://github.com/terraref/tutorials/blob/master/sensors/04-netCDF-tutorial.ipynb

**Comment by ac-gl-chris** [comment]
@hmb1 When does it suit you? I would prefer early in the morning at your side. Maybe we can use Skype.

**Comment by hmb1** [comment]
Hi Chris,
 you are up very early and i am up quite late 
would 10.00 GMT tomorrow suit ?
my Skype handle is henry.butowsky
...Henry

**Comment by ac-gl-chris** [comment]
Hi Henry,
would suit me yes. But I'm also available from 06.00 GMT so we could do it even earlier.
Going to add you in Skype then
Chris

**Comment by dlebauer** [comment]
Replaced by https://github.com/terraref/extractors-hyperspectral/pull/20

**Pull request closed without merging**
