### PR TITLE
Plantcv clowder extractor

### PR DESCRIPTION
**Pull request by nfahlgren**
## Description
This pull request adds/updates a script that will be run by a Clowder extractor. The script will analyze images that are stored in Clowder from the Danforth Center LemnaTec system using PlantCV. Results per image are posted back to Clowder as metadata. A summary traits file (CSV) is also posted back to Clowder.

## Motivation and Context
With an appropriate Clowder extractor, the code in this pull request will enable us to automate PlantCV analysis. This does not completely close, but is related to issues #31, #33, #36, and #68.

## How Has This Been Tested?
I have tested the code manually on individual Clowder Datasets. More testing will need to be done to integrate the code with an extractor.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dlebauer** [comment]
@max-zilla can you please review this pull request and either provide feedback or merge?

**Comment by max-zilla** [comment]
@nfahlgren took a look and things generally look good. good news is, extractor should simplify things a bit. I think I see two or maybe three extractors here,
1. Extractor for adding image metadata to a file based on filename (PlantcvClowderUploader.py) unless this is deprecated
2. Extractor for adding image file metadata fro PlantCV to individual files (PlantcvClowderIndoorAnalysis)
3. Extractor for adding traits.CSV table to a dataset based on those PlantCV file extractions (PlantcvClowderIndoorAnalysis)

2 and 3 could be one single dataset extractor or two separate extractors (one file, one dataset) depending on how we want to use them - we can discuss.

**PlantcvClowderIndoorAnalysis.py**
- main() fetches a list of files for a dataset, and calls get_metadata().
- get_metadata() will fetch metadata for each file and create an aggregate metadata object for the dataset. You referred to "deprecatedapi" but this is an artifact that will go away in production (we will use JSON-LD to properly identify each extractor - I can show you how)
- once ds metadata is generated a traits CSV is created based on image type and that CSV is uploaded into Clowder. This step involves PlantCV for side- and top-view images. 
- **in an extractor context** the extractor can listen on "*.dataset.added" for new files. when the extractor is triggered you'll have access to the list of files in the dataset - you can fetch their metadata and create the new dataset metadata in essentially the same way as before. 

**PlantcvClowderUploader.py**
- main() reads a SnapshotInfo.csv file to get a list of snapshots, creates a dataset based on the snapshot ID, and uploads the listed files to that dataset with metadata extracted based on filename parsing. 
- **in an extractor context**, your extractor can listen on image files and you really only need **metadata_to_json()**. the extractor will be notified when a new image file is uploaded and you'd basically just call this function on the filename (the extractor won't even need to download the file).

In both cases, we can use PyClowder to remove the need for you to implement your own utility functions (e.g. upload_file_to_clowder). This would mean if the Clowder API changes we can update PyClowder and you won't need to update your code each time. That can be a later change though.

I will merge this pull request after we briefly discuss on the call today, but the only other piece we might want to add is to use some of the hooks I've added to PyClowder to check whether a file/dataset already has metadata from this extractor and either replace or don't repeat the extraction data if so (rather than potentially ending up with duplicates of metadata). This is particularly useful for dataset extractors that are triggered whenever a file is added to a dataset.

**Comment by nfahlgren** [comment]
@max-zilla I think that all sounds good, let's definitely discuss. For PlantcvClowderUploader.py, I was not thinking about running it as an extractor because it's something I would run at Danforth Center to transfer data from the LemnaTec system here to UIUC. But, alternatively we could set up a Globus transfer like the MAC transfer and run this as an extractor.

**Comment by max-zilla** [comment]
After looking a bit closer, I want to check my understanding:

- this appears to get JSON-LD metadata from the list of files and create a json object that is then used to feed the images into PlantCV. The PlantCV outputs for each file are added to the file metadata, as well as used to create a traits.CSV file for the dataset. 
- where does the JSON-LD metadata come from that is fetched in get_metadata()? is this the result of your ClowderUploader script? I ask because there may be a timing issue here - we'll need to make sure that metadata is present before running this extractor. Based on what I'm about to propose we can account for this - we just make sure to add the metadata before adding the new file to a dataset (thus triggering the extractor)

Assuming the required metadata exists the extractor logic I propose is:
- listen on dataset.files added
- new event comes in, we get a list of files in the dataset
- for each image file, does it already have PlantCV metadata? if not, run the process_xx_images() functions to generate plantCV metadata. if it does, fetch metadata from Clowder. either way, add the PlantCV metadata to the overall dataset traits list
- if all the files already have PlantCV metadata AND the dataset already has an entry for this extractor, we don't need to do anything. there's no new information. if any images DON'T have PlantCV metadata however, we should remove current traits.CSV from dataset and replace with an updated copy that includes the new image metadata.
- when all files are done, use the dataset traits list to generate traits.CSV and add it to the dataset. since the extractor will only check for metadata in the images, in most cases this will trigger the extractor but it wont find any new stuff to generate so it will just quickly exit.

I think this puts us in good shape and should guarantee:
- adding new file to a dataset will result in an updated traits.CSV file for the dataset if appropriate
- adding new file that is unrelated (e.g. a text file) will not replicate unnecessary work
- each of the image files will have the filename metadata you generate before submission, as well as PlantCV extracted metadata that we create based on the filename metadata.
- by creating the file + adding metadata BEFORE adding it to the dataset, we control when the dataset extraction event fires and ensure we can add the filename metadata first.

What do you think?

**Comment by nfahlgren** [comment]
Right, so PlantcvClowderUploader.py reads datasets (snapshots) from the Danforth Center system. It has all the files and experimental metadata associated with the dataset and files. It creates a Collection and adds it to a Space. It creates a Dataset for each snapshot and adds it to the Collection. It uploads each file from a snapshot to the Dataset and sends experimental metadata along with the file upload. 

It will definitely be key to set up a mechanism where the extractor will only run once the full set of files and metadata is present in the dataset. We had discussed having the PlantcvClowderUploader.py script provide a metadata entry at the Dataset level that would specify the number of images that should be present for the Dataset to be complete.

**Comment by max-zilla** [comment]
I'm going to merge this and create a new issue around converting Noah's code here to an extracto:
https://github.com/terraref/computing-pipeline/issues/119

**Comment by nfahlgren** [comment]
@max-zilla okay for me to delete this feature branch?

**Comment by max-zilla** [comment]
@nfahlgren ok to delete if you want.

**Pull request merged**
