### PR TITLE
added matlab/octave scripts for processing PS2, NDVI, FLIR re issue #64

### PR DESCRIPTION
**Pull request by dlebauer**
## Description

Octave scripts on the control PC such that operators on site can view raw data (Vis, FLIR, PS2, Sensors) and make simple analyses and visualizations

## Motivation and Context

First step in pipeline to convert binary files for these sensors to image files.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by dlebauer** [comment]
@TinoDornbusch could you check that all scripts are in here: https://github.com/terraref/computing-pipeline/pull/110/files

A few questions:

* I did not find the GetStereoVis.m file, though perhaps @pless has one (?)
* I also only found one plotting script - for  NDVI
* NDVI code is marked as GPL-3. For code like this that is simple yet will become the first step for many workflows, could you please change this to an [MIT license](https://opensource.org/licenses/MIT) or MIT compatible license?

**Comment by TinoDornbusch** [comment]
@dlebauer  No idea how to change license. I am not a software developer.

**Comment by dlebauer** [comment]
@TinoDornbusch It's just the text in the header of two of the files. I can change it if it's ok w/ Lemnatec.

**Comment by TinoDornbusch** [comment]
@dlebauer  please do....Should I upload further updates as well?

**Comment by dlebauer** [comment]
Please do.

**Comment by dlebauer** [comment]
PS if you haven't used github yet, you can click the pencil (edit) icon here:  https://github.com/terraref/computing-pipeline/pull/110/files

You can also create a new file here: https://github.com/terraref/computing-pipeline/new/gh-64-bin2image

Or try github desktop, which is a good place to start https://desktop.github.com

You could try command line git but using one of the above GUIs provides a more friendly introduction

**Pull request merged**
