### PR TITLE
Plantcv clowder extractor

### PR DESCRIPTION
**Pull request by max-zilla**
This adds several enhancements/changes to the PlantCV processing script and extractor. The script has been generalized in places to allow functions to be called directly from command line or extractor and utilize same shared code wherever possible.

### CODE REVIEW

**Comment by robkooper** [comment]
@max-zilla can you assign the person that should give the OK and/or merge this pull request.

**Comment by max-zilla** [comment]
@yanliu-chn I'm assigning this to you, because Noah seems content with his script and I think the extractor is working. I know you've done some work on this before so I wanted to to get the chance to see before merging.

**Comment by nfahlgren** [comment]
@max-zilla should the folder extractor_with_avg_traits with two .pyc files be part of the merge? Otherwise looks good to me.

**Comment by max-zilla** [comment]
@nfahlgren no, i thought I took care of those - looks like they must've snuck it at some point (there are other PYC files I didn't commit, havent set up gitignore for them). Just removed them.

**Comment by nfahlgren** [comment]
@yanliu-chn just checking that you will merge right? Want to make sure no one is waiting on me. Thanks!

**Comment by max-zilla** [comment]
@nfahlgren i asked Yan to review, he's been out of the office. I'll go ahead and merge.

**Pull request merged**
