### PR TITLE
Demosaic extractor

### PR DESCRIPTION
**Pull request by ZongyangLi**
This extractor convert bin files from the stereoTop data to demosaic'ed geoTiff + jpgs files.

### CODE REVIEW

**Comment by robkooper** [comment]
Can you add a reviewer(s), the person that will check your code and make sure it does what it needs to do.

**Comment by ZongyangLi** [comment]
@max-zilla Could you please help me test and review this code on real datasets? I have tested it on my computer.

**Comment by abby621** [comment]
@robkooper @ZongyangLi @max-zilla I'm happy to work on our end to make sure that the code does what it needs to do too, but should the reviewer(s) be someone on our end (e.g., me) or someone on your end (e.g., Max)? My concern is primarily if there's some difference in environments that makes it not work when it's run on the production environment, despite it working as expected in our test environment, how we would go about debugging that. Or are you really just looking for verification from someone that "yes, this code takes in dataset x and produces geoTIFFs and jpgs"? Just looking for some clarity on the type of review you're looking for, if possible. Thanks!

**Comment by robkooper** [comment]
there can be multiple people that review, @abby621,  you can make sure the code does what it needs to do, @max-zilla  can look at make sure it runs here as an extractor.

**Comment by max-zilla** [comment]
@ZongyangLi I will test+review hopefully this afternoon. @abby621 I will let you know once I've done so and any things of note.

**Comment by max-zilla** [comment]
@ZongyangLi @abby621 took a look, wanted to ask a few Q's for my understanding.

- you look through files and check for "_dataset_metadata.json" first. were you testing with this at all? typically this will contain all metadata associated with a dataset, not just the lemnatec md you are expecting. it's technically possible that someone could upload lemnatec md into the metadata object (instead of uploading metadata.json file), we'd need to parse it first to find the specific sub-item we care about (and not some other extractor metadata). has this been discussed at all? for now, i just ignore _dataset_metadata.json because it wasn't working (i had metadata in the dataset but not the kind you need)
- why 2 separate extractors for JPG and TIFF? should they be separate scripts? we could combine them into one demosaic.py script and have one extractor do both parts, but I understand if we want to keep them as 2 separate pieces.

Some small tweaks I made:
- f.find() -> f.endswith() for finding the md/left/right filenames, to make match more precise. i was getting some false positives before adjusting.
- "import imp" is used to import demosaic.py from /stereoImager directory -> no longer need a 2nd copy of it in /extractors. config.py you can point to where it is. I will either do the same for bin_to_geotiff.py, or as asked above we can move that into demosaic.py

Most of this isn't a big deal, just to polish it. The demosaic.py extractor works otherwise. I'll test the bin_to_tiff extractor once I hear whether we can combine them or keep separate.

**Comment by abby621** [comment]
@max-zilla @ZongyangLi I'm confused on the first item -- is there any reason we can't just remove the check for "_dataset_metadata.json"? I am not as familiar with the specifics of the code, so perhaps I'm missing something, but aren't we just looking for three files that all start with the same string and end with _metadata.json, _right.bin and _left.bin? Max, do you have a recommended way of doing this (or am I correct that we should just drop the _dataset_metadata.json check)? @ZongyangLi can clarify, but I don't think there's any need to use "_dataset_metadata.json" for this -- we are only interested in the specific metadata associated with the left and right binary images from the stereo extractor.

As for the two separate extractors -- I think there should just be one script and one extractor.

**Comment by max-zilla** [comment]
@abby621 so the situation is, the raw data generates _left, _right, _metadata. 

The way the Maricopa->Illinois pipeline has been developed, the _metadata.json files are transferred to the filesystem in Illinois, but they are attached to the dataset containing _left and _right as metadata (i.e. not uploaded as a JSON file - sent as a JSON object that gets indexed in the Clowder database and shown in the UI as dataset metadata). I realize the distinction might be odd, but in order to use the various searching/indexing capabilites we need to extract the contents of _metadata.json.

SO the short answer is, if this is operating on data coming from Maricopa we need to support the _dataset_metadata.json file, so I think that does need to be checked first. That is fairly easy fix, I can make it - just generally speaking we aren't going to be uploading metadata.json files to the dataset directly because they are more useful as literal data associated with the dataset in the database.

We can still check for the metadata.json files so this extractor will work in contexts where people are manually uploading 3 files, but for MAC we will have 2 files + some metadata. 

I'll update to correctly handle existing dataset metadata and merge the two scripts, and we should have V1 ready for the meeting tomorrow.

**Comment by abby621** [comment]
@max-zilla @ZongyangLi Sounds good -- I think some of these dataset specifics are a little over our heads here, and we appreciate the support!

**Comment by ZongyangLi** [comment]
Extractor for JPG and TIFF are combined in one 'terra.bin_to_geotiff.py' script. I just leave 'terra.demosaic.py' and 'demosaic.py' here as an example @max-zilla  provided to me. Maybe we should delete it now.
I just follow the example(terra.demosaic.py) and make small modifications in finding input files(f.find()-->f.endswith())in my codes and tested. Now I realize that I should try another way to make match more precise, like parse the metadata, get the filename and remove the processed files from parameters['files']? If I make any misunderstanding, please let me know.

**Comment by max-zilla** [comment]
@ZongyangLi let's discuss during TERRA meeting tomorrow, I've made some changes I'm going to commit along the lines of what you describe.

**Comment by max-zilla** [comment]
@ZongyangLi @abby621 can you attach here the metadata.json file you were testing with? I have a Docker version of the extractor running but it's failing the tests - my metadata.json file is formatted differently and just has "Todo" where your script looks for the "position x [m]" fields and the like.

**Comment by ZongyangLi** [comment]
[https://drive.google.com/open?id=0B5QCp_Onc6nOOGw1aVhHdUFKYlE](url)
Here are a set of input files I was testing with for terra.bin_to_geotiff.py.

**Comment by ZongyangLi** [comment]
[deb8b36f-222e-477d-be8f-99ff92de4221_metadata.json.zip](https://github.com/terraref/computing-pipeline/files/388640/deb8b36f-222e-477d-be8f-99ff92de4221_metadata.json.zip)

**Comment by max-zilla** [comment]
@ZongyangLi @abby621 OK, just pushed a big update. I think this is ready. Will cover it on the call.

- bin_to_geotiff.py is now the main script, in /stereoImager. this is pointed to from the extractor (path to this script can be changed in config.py)
- one extractor calls bin_to_geotiff.py to generate both JPG and TIF
- removed demosaic.py, terra.bin_to_geotiff.py
- added Dockerfile and entrypoint.sh to build docker container version of this extractor. Docker container will install osgeo/GDAL, PIL, scipy, other dependencies itself so we don't have to worry about them.
- updated check_message() in terra.demosaic.py to be more strict - ensures left.bin and right.bin are present before passing on to process_dataset().
- if left/right/metadata aren't found, extractor will return false and won't write COMPLETED to the dataset metadata, so when the missing piece is added it will re-trigger. SEE NOTE BELOW

@robkooper we should discuss making extractor listen on multiple kinds of messages - in this case the final necessary piece could be a .json file (*.dataset.file.added) OR it could be metadata added to the dataset (*.metadata.added) so really this should trigger on either.

**Comment by ZongyangLi** [comment]
I will try these updates in my test environment.
Thank you very much for your help! I really appreciate it.

**Comment by max-zilla** [comment]
@ZongyangLi have you had a chance to take a look?

**Comment by ZongyangLi** [comment]
@max-zilla I had look through your update and successfully run this extractor in my testing environment. The extractor will generate both jpg and tiff if all the dataset are provided. I can get the output files by copying them from absolute path, but I may not download or visualize them in my clowder website. If it is not a problem, I agree that it is ready for #64 . 

These geotiff output files will be used to create a full field stitched map in #85 . As geo-information has been added into geotiff files, we just need a list to tell us which geotiff should be integrated into the full stitched map. I have prepared the main script for this, shall we pull this codes and move on #85 ?

Thanks!

**Comment by max-zilla** [comment]
@ZongyangLi that is probably just a result of the default Clowder permissions on your site - the production TERRA instance is public so we should not have the problem of being unable to download/visualize.

I will merge this after our meeting this morning and it sounds like #85 is the logical next step. Thanks!

**Pull request merged**
